# Generated by Django 4.0.2 on 2022-05-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('persons_amount', models.IntegerField()),
                ('register_persons_amount', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('rank', models.DecimalField(decimal_places=1, max_digits=2)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.category')),
                ('coordinate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('bankAccount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bankAccount', models.CharField(max_length=50)),
                ('building_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bankAccount', models.CharField(max_length=50)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.photo')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rank', models.DecimalField(decimal_places=1, max_digits=2)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrgEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.organizer')),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='photo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.photo'),
        ),
        migrations.CreateModel(
            name='FavouriteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.photo'),
        ),
    ]
