# Generated by Django 4.0.2 on 2022-02-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('persons_amount', models.IntegerField()),
                ('register_persons_amount', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('descrpition', models.TextField()),
                ('time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('rank', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
