# Generated by Django 4.0.2 on 2022-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descrpition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='rank',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
