# Generated by Django 4.0.2 on 2022-02-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0003_rename_descrpition_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event'),
            preserve_default=False,
        ),
    ]
