# Generated by Django 4.0.2 on 2022-02-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0006_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
    ]
