# Generated by Django 4.0.2 on 2022-02-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0007_remove_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user'),
            preserve_default=False,
        ),
    ]
