# Generated by Django 4.0.2 on 2022-02-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0009_remove_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user')),
            ],
        ),
    ]
