# Generated by Django 4.0.2 on 2022-02-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0011_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.photo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rank', models.DecimalField(decimal_places=1, max_digits=2)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.user')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
            ],
        ),
    ]
