# Generated by Django 4.0.2 on 2022-02-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0012_event_photo_id_user_photo_id_review_favouriteevents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinate_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.coordinate'),
            preserve_default=False,
        ),
    ]
