# Generated by Django 4.0.2 on 2022-02-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0013_remove_coordinate_event_id_event_coordinate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('bankAccount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bankAccount', models.CharField(max_length=50)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.organization')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.photo')),
            ],
        ),
        migrations.CreateModel(
            name='OrgEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.event')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.organizer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.category'),
            preserve_default=False,
        ),
    ]
