# Generated by Django 4.0.2 on 2022-02-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0014_category_organization_organizer_orgevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventodor_back.organizer'),
            preserve_default=False,
        ),
    ]
