# Generated by Django 4.0.2 on 2022-02-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0015_event_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
