# Generated by Django 4.0.2 on 2022-02-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventodor_back', '0016_rename_photo_id_event_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='coordinate_id',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='org_id',
            new_name='organizer',
        ),
    ]
